service: logging

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  role: arn:aws:iam::793076161695:role/app-logging-role

functions:
  dispatchErrors:
    handler: handler.dispatchErrors
    events:
      - sns: arn:aws:sns:us-east-1:793076161695:PRODUCTION_ERRORS